name: "Test @notesnook/core"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "packages/core/**"
      # re-run workflow if workflow file changes
      - ".github/workflows/core.tests.yml" 
  pull_request:
    types:
      - "ready_for_review"
      - "opened"
      - "synchronize"
      - "reopened"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Prepare environment
        run: |
          npm ci --no-audit
      - name: Add environment variables
        run: |
          echo "EMAIL=${{ secrets.USER_EMAIL }}" >> $GITHUB_ENV
          echo "PASSWORD='${{ secrets.USER_PASSWORD }}'" >> $GITHUB_ENV
          echo "HASHED_PASSWORD=${{ secrets.USER_HASHED_PASSWORD }}" >> $GITHUB_ENV
      - name: Run all @notesnook/core tests
        run: npx nx test:e2e @notesnook/core
